{% set version = "5.2.1" %}

package:
  name: iris-ued
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  sha256: ee10a8841449fa6a805493287fb6d366ce254637b7ceb0771902892d57b7e2c2

build:
  number: 1
  skip: True  # [py<36 or linux]
  entry_points:
    - iris = iris.gui:run
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.12,<2
    - scipy >=1.0.0,<2
    - h5py >=2.10.0,<3
    - pyqt >=5,<6
    - qdarkstyle ==2.7
    - scikit-ued >=2.0.2, <2.1.0
    - pyqtgraph >=0.10,<1
    - npstreams ==1.6.2
    - crystals ==0.6.6

test:
  imports:
    - iris
    - iris.gui

about:
  home: http://iris-ued.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ultrafast electron scattering data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron scattering data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: 'https://iris-ued.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/iris-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
