{% set version = "5.1.3" %}

package:
  name: iris-ued
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  sha256: 28e7a26005fddbc85cd32a8d0b2a07a57eb92234e0050c9e3100f881a9cba9fd

build:
  number: 2
  skip: True  # [py<36 or linux]
  entry_points:
    - iris = iris.gui:run
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.12,<2
    - scipy >=1.0.0,<2
    - h5py >=2.6.0,<3
    - pyqt >=5,<6
    - scikit-ued ==1.0.1.1
    - pyqtgraph >=0.10,<1
    - npstreams ==1.6,<2

test:
  imports:
    - iris
    - iris.gui

about:
  home: http://iris-ued.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ultrafast electron scattering data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron diffraction data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: 'https://iris-ued.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/iris-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
