{% set version = "5.2.4" %}

package:
  name: iris-ued
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  sha256: aee05cdd9174e2dd777508411c60d5115cf3174f3cb17a511272e67a31f4026f

build:
  number: 1
  skip: True  # [py<36]
  entry_points:
    - iris = iris.gui:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.12,<2  # [py<38]
    - numpy >=1.17,<2  # [py>=38]
    - scipy >=1.0.0,<2
    - h5py >=2.10.0,<4
    - pyqt >=5,<6
    - qdarkstyle >=2.8.1, <3
    - scikit-ued >=2.0.3, <3
    - pyqtgraph >=0.11,<1
    - npstreams >=1.6.2,<2
    - crystals >=1.1.2, <2

test:
  imports:
    - iris
    - iris.gui
  commands:
    - python -m unittest discover --buffer

about:
  home: http://iris-ued.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Ultrafast electron scattering data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron scattering data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: 'https://iris-ued.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/iris-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
