{% set version = "5.1.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "89aef749d575c10f54171600bfcb3525b065f1aebb80ece59267dcbe6a52a4ec" %}

package:
  name: 'iris-ued'
  version: '{{ version }}'

source:
  fn: 'iris-ued-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True  # [ py<36 or linux ]
  number: 0
  entry_points:
    - iris = iris.gui:run
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.12
    - scipy >=0.17
    - h5py >=2.6.0
    - pyqt >=5
    - scikit-ued >=1.0.1.1
    - pyqtgraph >=0.10
    - npstreams >=1.5.2

test:
  imports:
    - iris
    - iris.gui

about:
  home: http://iris-ued.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: Ultrafast electron diffraction data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron diffraction data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: 'https://iris-ued.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/iris-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
