appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gLu4yLejsD0b+oZUxLXDMPw5GG4JBUo9rsm5d/eqfbDKIcJpMP4TG902IQQM6FbdjTV+njoBnVhR+QF65Ma5e9JxWyTtz82dqPt0znNInM02eDo9bL2yN3H2pqA0toa0CDJPpiUUJiBQGI+jQE1CUeAd8E4ahCA0cZ9mrgC1P+98iGkVAXs7u82UUJIby47sY4D+SWltb0L44+oLtxqjbgSDpJ9O7OlNVndTbN0u8rH0NdNvR5qybW01hO56b2sLM+r+heRAcy1+WpuL11BHALAzR+m4VZk68EssYrPa3YUC9oyqvbvyt7o9/6ptxdrKV+zuIyIUlYsmgF+pEbl0/gW+PImTPkoPPzoJW6iYLDmuPhLrJEhgnmQv4nOFbUpUDS1s+Bw4dX1auMaIcGDVfHrNT5hKTr/ydgsW0rFmJI90rWGtVWsU+Rd2q4nWqIwUSEIQv2wWiblR0LbvwnvG3wscnwVFD2vrSFd4+hJEKm0OufBczuzZMJ3qXVdGth4uksDBqah2jv7aDKB+26pNPEt9t5ptyjNgbTy0Cr1ph6hSdJaBDOm5N5eGgggItB0lh0T7Rib4aPuHJO9hivYrUi+f/UwDC9ytwuDDivUNd8CnhPSU1ywI0UTC6UEKg0/QFazw6bGBvgrmkUb4Q9X/Vt8v9x3Mm3NunsPhmm5lBGs=}
provider:
  win: azure
