travis:
  secure:
    BINSTAR_TOKEN: hRgM2bf1kdk5ZodzxbJLyd+JPN+MKmQMYQpvreZAdEDdBcsICcpUYALIU78mXzFJWRrMUUfN+t5FqIf2L5lI+9mFH8Oi1ti9lvDMs+i21pwozdHpBTRq3OlZZCfs5VbPIdsSMy5SHErqX2v0Tqv3HMbC2xPjfD6rVvJH+NT3+BkgYIA1oksOqc2ZTHVBsN10JCz1eO4+lZbrAhJyMoEonNtagu2wRpVijMxS3sanThMTGz1Cjs03MDyfYVK5NcrPPMjZ7NfX7LPSdMErivt+iPdncjAHMWSLTC/dvRsw5Xku80IT76RYS5hXSv5Ne5h4Ys3KUKgtLo6Wpeb9kdGC8akqjM+iVTZZNbgCHwef61pRvtRVTM+pDlDFBBtH6+xCHOtpxiEBIl0tfDsF23J4xeIw0ne/yw0PYQTVpgDBWWvJBv4iP0eUh2oTWg+Du1hA9i6Nb4Yza1VrcEaJhslh0frXUr+ve3yKGeK8rXoWXyFVAMXalA80WG7QyWP+fcv3zWLhnTl7WfVkWpMNEstfybQLLUiOV1Q/B4bkP/LZL0or7HagudRBdahEmUwrhwuUCIYauajcvF6Rx6Ifkx35RX9xsX/2uT+ItN8djg9fUxPETMK6XmFrS3TKlFEZf4hS2vs7PcZRWiquZK6gotxtKOV06TPsCJ98P0zrJJsjB0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
